apiVersion: v1
kind: Service
metadata:
  name: canary-staging
  namespace: staging
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-staging
